### PR TITLE
MIT License

### PR DESCRIPTION
**Pull request by joekain**

### CODE REVIEW

**Comment by joekain** [comment]
Fixes #12

**Comment by knewter** [comment]
Can you update the name on the copyright to Josh Adams by chance? :)  Then I'll merge it gladly.  Thanks so much!

**Comment by joekain** [comment]
@knewter, oops sorry about that :)  I just copied the file from one of my other projects and forgot that it had a copyright holder at all.

Should be fixed now.  Thanks.

**Comment by knewter** [comment]
Woo, thanks :)

**Pull request merged**
