### PR TITLE
First pass at cleaning up the design.

### PR DESCRIPTION
**Pull request by keathley**
This is my first pass at some style changes. Its still very much a WIP but I wanted to get some initial feedback on what I was playing with (note that I'm using 'nintendo' as my search term so that more data comes through):
# Large:

screenshot 2015-10-26 01 41 57
# Medium:

screenshot 2015-10-26 01 41 48
# Small:

screenshot 2015-10-26 01 41 15

I removed semantic in favor of just rolling my own stuff. Its a simple enough layout that I felt it didn't warrant the framework. Currently this will only work in webkit because thats the only vendor prefix I included. My plan is to fix this with autoprefixer (see below).

I'd love any feedback that you have.
## Stuff that still needs to be done:
- [x] The vertical rhythm and whitespace is off for certain breakpoints and could be tightened/loosened.
- [x] Add autoprefixer to brunch so we can drop the vendor prefixes.
- [x] The header needs work. There should be more of a call to action.
- [x] We're missing a footer (is this something we need or is it supposed to infinite scroll?)
- [ ] The card font could be tweaked and links could be stripped or formatted with markdown.
- [x] Some of the styles are duped and could be better broken down into components.
- [x] There are probably enough react components that we could pull them into their own files (but also none of them are complicated so...meh?)
- [x] A transition for when new cards appear would be nice (and is easy to add with react).
- [x] Fix broken test that was looking for the old tagline.

### CODE REVIEW

**Comment by knewter** [comment]
I like it a lot so far.  I think a footer would be useful just for attribution mostly ("this is an @elixirsips @knewter @keathley etc joint, here's the github url if you want to contribute, etc")

**Comment by knewter** [comment]
I don't much care for infinite scroll tbh, esp. with how fast pagination should be on this :)

**Comment by knewter** [comment]
I love the idea of a simple transition when new cards appear

**Comment by keathley** [comment]
Do we need to include the `priv` dir for deployment purposes?

**Comment by knewter** [comment]
We shouldn't.  If we currently do, I can switch to a buildpack that builds
the assets.  I honestly don't recall :-\

On Mon, Oct 26, 2015 at 11:19 PM, Chris Keathley notifications@github.com
wrote:

> Do we need to include the priv dir for deployment purposes?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/knewter/elixir_friends/pull/5#issuecomment-151371056.

## 

_Josh Adams_
CTO | isotope|eleven http://www.isotope11.com
[cell](205) 215-3957
[work](877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by keathley** [comment]
I'll remove it from source control

**Comment by keathley** [comment]
Latest screenshots:

Large screen

screenshot 2015-10-28 00 14 17

I've changed the color palette slightly for the header and tagline.

screenshot 2015-10-27 23 57 12

I've also updated the card fonts, paddings, and some layout work. I felt like the usernames were getting lost with the old layout and I wanted to give people more ownership over their tweets and pictures. I also tweaked the shadow just slightly.

screenshot 2015-10-27 23 56 47

Also added a super basic footer. Not sure how you want to do the attribution @knewter since you've done all the hard work. I just followed what you posted a few comments up. Lemme know if you want to change it.

screenshot 2015-10-27 23 58 03

I ended up swapping out Brunch for Webpack. I had mixed feelings about this but Brunch doesn't support npm modules yet and most of the react ecosystem uses npm to distribute packages. Luckily webpack is easy to setup and works just as well with phoenix.

Cards will now fade in when they initially mount in the DOM and when they are pushed down from the server.

There is a bit of a hitch when the app initially loads into the DOM. I'd like to optimize it but I'm not sure that its much of a blocker (we could get around most of it by pre-loading some data in the DOM when the page is rendered). Otherwise I think we're getting close. Let me know what you think though.

**Comment by knewter** [comment]
I think it's looking amazing :)  The footer is good as is imo.  When
running it locally I'm getting an issue.  I'm assuming I can resolve it by
updating the url to mention the port in the environment, it's just odd that
I haven't run into this before :)  I'll figure it out, and then I'll figure
out what I need to do to make sure the assets are compiled on deploy, then
I think we're pretty good to go.  Superb work :)

```
[error] Could not check origin for Phoenix.Socket transport.

This happens when you are attempting a socket connection to
a different host than the one configured in your config/
files. For example, in development the host is configured
to "localhost" but you may be trying to access it from
"127.0.0.1". To fix this issue, you may either:

  1. update [url: [host: ...]] to your actual host in the
     config file for your current environment (recommended)

  2. pass the :check_origin option when configuring your
     endpoint or when configuring the transport in your
     UserSocket module, explicitly outlining which origins
     are allowed:

        check_origin: ["https://example.com",
                       "//another.com:888", "//other.com"]
```

On Tue, Oct 27, 2015 at 11:09 PM, Chris Keathley notifications@github.com
wrote:

> Latest screenshots:
> 
> I've changed the color palette slightly for the header and tagline.
> 
> [image: screenshot 2015-10-27 23 57 12]
> https://cloud.githubusercontent.com/assets/1642095/10779411/cb8bff20-7d06-11e5-9cc1-03576c576afd.png
> 
> I've also updated the card fonts, paddings, and some layout work. I felt
> like the usernames were getting lost with the old layout and I wanted to
> give them more ownership over their tweets and pictures. I also tweaked the
> shadow just slightly.
> 
> [image: screenshot 2015-10-27 23 56 47]
> https://cloud.githubusercontent.com/assets/1642095/10779440/3b1e90a0-7d07-11e5-85d3-b48ac7c0bb3c.png
> 
> Also added a super basic footer. Not sure how you want to do the
> attribution @knewter https://github.com/knewter since you've done all
> the hard work. I just followed what you posted a few comments up. Lemme
> know if you want to change it.
> 
> [image: screenshot 2015-10-27 23 58 03]
> https://cloud.githubusercontent.com/assets/1642095/10779450/60d4cc10-7d07-11e5-9909-d9099f8bab0e.png
> 
> I ended up swapping out Brunch for Webpack. I had mixed feelings about
> this but Brunch doesn't support npm modules yet and most of the react
> ecosystem uses npm to distribute packages. Luckily webpack is easy to setup
> and works just as well with phoenix.
> 
> Cards will now fade in when they initially mount in the DOM and when they
> are pushed down from the server.
> 
> There is a bit of a hitch when the app initially loads into the DOM. I'd
> like to optimize it but I'm not sure that its much of a blocker (we could
> get around most of it by pre-loading some data in the DOM when the page is
> rendered). Otherwise I think we're getting close. Let me know what you
> think though.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/knewter/elixir_friends/pull/5#issuecomment-151716817.

## 

_Josh Adams_
CTO | isotope|eleven http://www.isotope11.com
[cell](205) 215-3957
[work](877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by keathley** [comment]
I haven't seen that issue but I'll see if I can reproduce it locally. Glad that you like it!

**Comment by keathley** [comment]
I cleared my compiled assets and tried again but I wasn't able to repro that error.

**Comment by knewter** [comment]
I'll try to figure it out.  I want to push this out, I just need to make
sure I have the time to sort through the asset compilation issue that will
likely come up :)

On Wed, Oct 28, 2015 at 7:02 PM, Chris Keathley notifications@github.com
wrote:

> I cleared my compiled assets and tried again but I wasn't able to repro
> that error.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/knewter/elixir_friends/pull/5#issuecomment-152035925.

## 

_Josh Adams_
CTO | isotope|eleven http://www.isotope11.com
[cell](205) 215-3957
[work](877) 476-8671 x201

[mail]
3800 Colonnade Pkwy
Suite 140
Birmingham, AL 35242

**Comment by keathley** [comment]
In order to speed up the perceived loading time for the site I've preloaded the first page of entries into the window on the index action. When the react app mounts it pulls the preloaded data out of the window and passes it down to its child components as props. I also removed the redundant ajax call. In theory the extra call doesn't hurt anything. React will get new state but it won't re-render since nothing has changed. However, since there's no reason to do it I just opted to remove it. It also removes jquery which will lighten up the asset bundle.

Preloading this data could be solved with some isomorphic JS solution. But I figured I would leave that for a later day ;)

**Pull request merged**
